- name: DEBUG MESSAGE
  ansible.builtin.debug:
    msg: this is number {{ count }} when the task file has been imported/included

- name: IMPORT CHECK
  ansible.builtin.debug:
    msg: I have been imported
  when: i_import

- name: INCLUDE CHECK
  ansible.builtin.debug:
    msg: I have been included
  when: i_include
